### ISSUE TITLE
Storybook build process broken

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#12]
In order to get our global scss classes and variables available in storybook stories, we've updated the webpack config for storybook in `main.js` this uses `sass-resources-loader` to inject our global scss so it's available to all components. 

While the `yarn storybook` command works properly and produces local storybook development build, the production build as made by `yarn build-storybook` command is now broken due to this same additional scss config. 

Below is the logged error when we run the build process.

```
=> Failed to build the preview
ERR! ./src/main.scss
ERR! Module build failed (from ./node_modules/react-scripts/node_modules/mini-css-extract-plugin/dist/loader.js):
ERR! ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ERR! Error: Didn't get a result from child compiler
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/mini-css-extract-plugin/dist/loader.js:144:23
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:343:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1414:32
ERR!     at eval (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:316:20
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:367:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:182:20
ERR!     at context.callback (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/mini-css-extract-plugin/dist/loader.js:144:14
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:343:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1414:32
ERR!  @ ./src/components/colors/Colors.stories.jsx 4:114-138
ERR!  @ ./src sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.jsx\/?)$
ERR!  @ ./.storybook/generated-entry.js
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/generated-entry.js
ERR! ./src/components/colors/colors.scss
ERR! Module build failed (from ./node_modules/react-scripts/node_modules/mini-css-extract-plugin/dist/loader.js):
ERR! ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ERR! Error: Didn't get a result from child compiler
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/mini-css-extract-plugin/dist/loader.js:144:23
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:343:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1414:32
ERR!     at eval (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:316:20
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:367:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:182:20
ERR!     at context.callback (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/mini-css-extract-plugin/dist/loader.js:144:14
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:343:11
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/palmetto/Documents/dev/palmetto/palmetto-components/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:1414:32
ERR!  @ ./src/components/colors/Colors.stories.jsx 4:138-160
ERR!  @ ./src sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.jsx\/?)$
ERR!  @ ./.storybook/generated-entry.js
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/generated-entry.js
(node:32519) UnhandledPromiseRejectionWarning: [object Object]
(node:32519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by juanfabrega** [comment]
Fixed with latest build tooling done for https://github.com/palmetto/palmetto-components/issues/13
